class Scheduler:

 def __init__(self, JOB_NAME, PATH_TO_STDOUT, PATH_TO_STDERR, WALLTIME, QUEUE_NAME, ACCOUNT_NAME, TOTAL_NODES, CORES_PER_NODE):
    self.JOB_NAME = JOB_NAME
    self.PATH_TO_STDOUT = PATH_TO_STDOUT
    self.PATH_TO_STDERR = PATH_TO_STDERR
    self.WALLTIME = WALLTIME
    self.QUEUE_NAME = QUEUE_NAME
    self.ACCOUNT_NAME = ACCOUNT_NAME
    self.TOTAL_NODES = TOTAL_NODES
    self.CORES_PER_NODE = CORES_PER_NODE    