ecflow:
  suitedef:
    suite_workflow:
      vars:
        WORKFLOW_VAR: production
      family_data_prep:
        task_fetch:
          script:
            body: echo Fetching data...
          trigger: "1==1"
        task_process:
          script:
            body: echo Processing data...
          trigger: /workflow/data_prep/fetch == complete
      task_run_model:
        script:
          body: echo Running model...
        trigger: /workflow/data_prep == complete
