package:
  name: uwtools
  version: 1.0.1
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0 # <= always reset to 0 when incrementing version
requirements:
  host:
    - pip
  run:
    - boto3 1.22.*
    - f90nml 1.4.*
    - jinja2 3.0.*
    - jsonschema 4.17.*
    - lxml 4.9.*
    - python {{ release }}
    - pyyaml 6.0.*
test:
  requires:
    - black 23.3.*
    - coverage 7.2.*
    - docformatter 1.7.*
    - isort 5.12.*
    - jq 1.6.*
    - mypy 1.4.*
    - pylint 2.17.*
    - pytest 7.4.*
about:
  license: LGPL
