{% set info = load_file_data("uwtools/resources/info.json") %}
{% set pymin = "3.9" %}

package:
  name: uwtools
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - python {{ pymin }}
    - setuptools
  run:
    - f90nml 1.4.*
    - iotaa 1.1.*
    - jinja2 3.1.*
    - jsonschema >=4.18,<4.24
    - lxml 5.2.*
    - python >={{ pymin }},<3.13
    - pyyaml 6.0.*
    - requests 2.32.*
test:
  requires:
    - black 24.10.*
    - docformatter 1.7.*
    - isort 6.0.*
    - jq 1.7.*
    - make 4.4.*
    - mypy 1.15.*
    - pylint 3.3.*
    - pytest 8.3.*
    - pytest-cov 6.0.*
    - pytest-xdist 3.6.*
    - python {{ pymin }}
about:
  license: LGPL
