{% set info = load_file_data("uwtools/resources/info.json") %}

package:
  name: uwtools
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  build:
    - pip
  run:
    - f90nml 1.4.*
    - iotaa 0.8.*
    - jinja2 3.1.*
    - jsonschema 4.22.*
    - lxml 5.2.*
    - python >=3.9,<3.13
    - pyyaml 6.0.*
test:
  requires:
    - black 24.4.*
    - docformatter 1.7.*
    - isort 5.13.*
    - jq 1.7.*
    - make >=3.8
    - mypy 1.10.*
    - pylint 3.2.*
    - pytest 8.2.*
    - pytest-cov 5.0.*
    - pytest-xdist 3.5.*
about:
  license: LGPL
