package:
  name: uwtools
  version: 2.0.0
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0 # <= always reset to 0 when version changes
requirements:
  host:
    - pip
  run:
    - f90nml 1.4.*
    - jinja2 3.1.*
    - jsonschema 4.20.*
    - lxml 4.9.*
    - python >=3.9,<3.12
    - pyyaml 6.0.*
test:
  requires:
    - black 23.11.*
    - coverage 7.3.*
    - docformatter 1.7.*
    - isort 5.13.*
    - jq 1.7.*
    - make >=3.8
    - mypy 1.8.*
    - pylint 3.0.*
    - pytest 7.4.*
about:
  license: LGPL
