package:
  name: uwtools
  version: 1.0.0
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0
requirements:
  host:
    - pip
  run:
    - boto3 1.22.*
    - f90nml 1.4.*
    - jinja2 3.0.*
    - jsonschema 4.17.*
    - python >=3.8,<3.12
    - python {{ release }}
    - pyyaml 6.0.*
test:
  requires:
    - black 23.3.*
    - coverage 7.2.*
    - docformatter 1.7.*
    - isort 5.12.*
    - mypy 1.4.*
    - pylint 2.17.*
    - pytest 7.4.*
about:
  license: LGPL
