#!/bin/bash -eux

unformatted() { 
    set -x
    make format
    test -z "$(git status --porcelain)"
}

export -f unformatted

source conda/etc/profile.d/conda.sh
conda activate

CONDEV_SHELL_CMD=unformatted condev-shell
