#!/bin/bash -ae

unformatted() {
  set -x
  make format
  test -z "$(git status --porcelain)"
}

source /tmp/conda/etc/profile.d/conda.sh
conda activate
set -x
CONDEV_SHELL_CMD=unformatted condev-shell

echo Hello World!
