#!/bin/bash -eux

url=https://github.com/conda-forge/miniforge/releases/download/23.1.0-4/Miniforge3-23.1.0-4-Linux-x86_64.sh
wget --no-verbose $url
bash $(basename $url) -bfp conda
(
  set -e +ux
  source conda/etc/profile.d/conda.sh
  conda activate
  conda install -q -y -c maddenp --repodata-fn repodata.json anaconda-client condev=0.6.1
)
