#!/bin/bash -eux

f=Miniforge3-Linux-x86_64.sh
wget --no-verbose https://github.com/conda-forge/miniforge/releases/latest/download/$f
bash $f -bfp conda
(
  set -e +ux
  source conda/etc/profile.d/conda.sh
  conda activate
  conda install -q -y -c maddenp --repodata-fn repodata.json condev=0.3.0
)
