# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
conda:
  environment: docs/environment.yml
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
