name: workflow_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9*
  - boto3=1.22*
  - black
  - f90nml=1.4*
  - jinja2=3.0*
  - numpy=1.21*
  - pylint
  - pytest
  - pyyaml=6.0*
  - tox
