#!/bin/bash -eu

echo "=> Formatting code"
ruff format src

echo "=> Sorting imports"
ruff check --select I --fix src

echo "=> Formatting docstrings"
(cd src && docformatter . || test $? -eq 3)

echo "=> Formatting JSON"
for f in $(find src -not -path "*/.*" -type f -name "*.json" -o -name "*.jsonschema"); do
  jq -S . $f >$f.new || (echo "    in $f" && rm $f.new && false)
  cmp --quiet $f.new $f && rm $f.new || mv $f.new $f
done
