#!/bin/bash -eu

echo "=> Running black"
black src

echo "=> Running isort"
isort -q src

echo "=> Running docformatter"
(cd src && docformatter . || test $? -eq 3)

echo "=> Running jq"
for f in $(find src -not -path "*/.*" -type f -name "*.json" -o -name "*.jsonschema"); do
  jq -S . $f >$f.new || (echo "    in $f" && rm $f.new && false)
  cmp --quiet $f.new $f && rm $f.new || mv $f.new $f
done
