pipeline {
    agent none
    stages {
        stage('Run UFS Workflow Tools') {
            parallel {
                stage('Run UFS Workflow tools on Cheyenne') {
                    agent {
                        label "cheyenne"
                    }
                    steps {
                      cleanWs()    
                      checkout changelog: false, poll: false, scm: scmGit(branches: [[name: 'develop']], extensions: [], gitTool: 'Default', userRemoteConfigs: [[url: 'https://github.com/ufs-community/workflow-tools']])
                      sh '''
                            module use /glade/work/epicufsrt/contrib/miniconda3/modulefiles
                            module load miniconda3/4.12.0
                            conda activate workflow_tools

                            ${WORKSPACE}/.cicd/jobs/lint_and_test.sh
                      '''
                    }
                }
                
                stage('Run UFS Workflow tools on Jet') {
                    agent {
                        label "jet"
                    }
                    steps {
                       cleanWs()    
                       checkout changelog: false, poll: false, scm: scmGit(branches: [[name: 'develop']], extensions: [], gitTool: 'Default', userRemoteConfigs: [[url: 'https://github.com/ufs-community/workflow-tools']])    
                       sh '''
                          module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/miniconda3/modulefiles
                          module load miniconda3/4.12.0
                          conda activate workflow_tools

                          ${WORKSPACE}/.cicd/jobs/lint_and_test.sh
                      '''
                    }
                }
                
               stage('Run UFS Workflow tools on Hera') {
                   agent {
                       label "hera"
                   }
                   steps {
                       cleanWs()
                       checkout changelog: false, poll: false, scm: scmGit(branches: [[name: 'develop']], extensions: [], gitTool: 'Default', userRemoteConfigs: [[url: 'https://github.com/ufs-community/workflow-tools']])
                       sh '''
                       module use /scratch1/NCEPDEV/nems/role.epic/miniconda3/modulefiles
                       module load miniconda3/4.12.0
                       conda activate workflow_tools

                       ${WORKSPACE}/.cicd/jobs/lint_and_test.sh
                       '''
                   }
               }
               stage('Run UFS Workflow tools on Orion') {
                   agent {
                       label "Orion"
                   }
                   steps {
                       cleanWs()
                       checkout changelog: false, poll: false, scm: scmGit(branches: [[name: 'develop']], extensions: [], gitTool: 'Default', userRemoteConfigs: [[url: 'https://github.com/ufs-community/workflow-tools']])
                       sh '''
                       module use /work/noaa/epic-ps/role-epic-ps/miniconda3/modulefiles
                       module load miniconda3/4.12.0
                       conda activate workflow_tools

                       ${WORKSPACE}/.cicd/jobs/lint_and_test.sh
                       '''
                   }
               }
            }
        }
    }
}
