"""
Utilities for interacting with external processes.
"""

from __future__ import annotations

from pathlib import Path
from subprocess import PIPE, STDOUT, Popen
from typing import TYPE_CHECKING

from uwtools.logging import INDENT, log

if TYPE_CHECKING:
    from collections.abc import Callable


def run_shell_cmd(
    cmd: str | list[str],
    callback: Callable[[Popen], None] | None = None,
    cwd: Path | str | None = None,
    env: dict[str, str] | None = None,
    executable: str | None = None,
    log_output: bool = False,
    quiet: bool = False,
    start_new_session: bool = False,
    taskname: str | None = None,
) -> tuple[bool, str]:
    """
    Run a command in a shell.

    :param cmd: The command to run.
    :param callback: Called with the ``Popen`` process object.
    :param cwd: Change to this directory before running the command.
    :param env: Environment variables to set before running the command.
    :param executable: Interpreter to run command in (e.g. "/bin/bash").
    :param log_output: Log output from successful command? (Error output is always logged.)
    :param quiet: Log ``INFO`` messages as ``DEBUG``.
    :param start_new_session: Run process in a new session?
    :param taskname: Name of task executing this command, for logging.
    :return: Success indication and combined ``stdout`` / ``stderr``.

    The ``Callable`` specified by the ``callback`` argument will be called once with the ``Popen``
    object as soon as it is available; i.e. it may be called while the command is running, and does
    not wait for the command to complete.

    Use ``executable`` to use a shell other than the ``subprocess.Popen`` default, ``/bin/sh``.

    It is assumed that ``uwtools.api.loggin.use_uwtools_logger`` has previously been called to set
    up logging if ``log_output`` is ``True``.

    The ``start_new_session`` argument is connected directly to the argument of the same name when
    ``subprocess.Popen`` is called. Among other potential use cases, it prevents the command from
    receiving a ``SIGINT`` generated by a user Ctrl-C, useful when the command is running in a
    thread and the main control thread should handle the interrupt.

    If ``taskname`` is provided, log messages will be prefixed with ``[<taskname>]``.
    """
    pre = f"[{taskname}] " if taskname else ""
    logfunc = log.debug if quiet else log.info
    logfunc("%sRunning: %s", pre, cmd)
    if cwd:
        logfunc("%s  in directory", pre)
        logfunc("%s    %s", pre, cwd)
        cwd = Path(cwd)
        cwd.mkdir(parents=True, exist_ok=True)
    if env:
        logfunc("%s  with environment", pre)
        for k in sorted(env):
            logfunc("%s    %s=%s", pre, k, env[k])
    kwargs: dict = dict(
        cwd=cwd,
        encoding="utf=8",
        env=env,
        shell=isinstance(cmd, str),
        start_new_session=start_new_session,
        stderr=STDOUT,
        stdout=PIPE,
        text=True,
    )
    if executable:
        kwargs["executable"] = executable
    proc = Popen(cmd, **kwargs)  # noqa: S603
    if callback:
        callback(proc)
    output, _ = proc.communicate()  # blocking call
    success = proc.returncode == 0
    if not success:
        logfunc = log.error  # log remaining messages as errors
        logfunc("%sFailed with status: %s", pre, proc.returncode)
    if output and (log_output or not success):
        logfunc("%sOutput:", pre)
        for line in output.strip().split("\n"):
            logfunc("%s%s%s", pre, INDENT, line)
    return success, output
