#!/usr/bin/env -S bash -eu

if [[ -d conda/ ]]; then
  source conda/etc/profile.d/conda.sh
else
  fn=Miniforge3-Linux-$(uname -m).sh
  wget https://github.com/conda-forge/miniforge/releases/download/26.3.2-3/$fn
  bash $fn -bfp conda
  rm -v $fn
  source conda/etc/profile.d/conda.sh
  cmd="conda create -y -n demo bash_kernel jq jupyterlab tree oar-gsl::wxvx"
  if [[ -v $PRERELEASE ]]; then
    $cmd
    conda install -y conda-build
    reporoot=$(git rev-parse --show-toplevel)
    make -C $reporoot package
    conda install --name demo local::uwtools
  else
    $cmd ufs-community::uwtools
  fi    
conda activate demo
python -m bash_kernel.install
export BASEDIR=$PWD
jupyter lab ecflow.ipynb
