COMMANDS = $(wildcard *.cmd)
OUTPUTS  = $(COMMANDS:cmd=out)

.PHONY: all $(OUTPUTS)

all: $(OUTPUTS)

$(OUTPUTS):
	@bash $(basename $@).cmd >$@ 2>&1 | true

%.out: %.txt %.yaml
	@bash $< >$@ 2>&1 | true
