export UWTOOLS_TIMESTAMP = 2025-01-02T03:04:05

COMMANDS = $(wildcard *.cmd)
OUTPUTS  = $(COMMANDS:cmd=out)

.PHONY: all $(OUTPUTS)

all: $(OUTPUTS)

$(OUTPUTS):
	@bash $(basename $@).cmd >$@ 2>&1 | true
