#!/usr/bin/env bash

f() { # PM FIXME
  conda install -y conda-build
  pushd ~/git/uwtools/
  make package
  popd
}
  
set -eu
fn=Miniforge3-Linux-$(uname -m).sh
wget https://github.com/conda-forge/miniforge/releases/download/26.3.2-3/$fn
bash $fn -bfp conda
rm -v $fn
source conda/etc/profile.d/conda.sh
f # PM FIXME
conda create -y -n demo -c local -c oar-gsl bash_kernel jq jupyterlab tree uwtools=2.18 wget wxvx=0.7
conda activate demo
python -m bash_kernel.install
jupyter lab ecflow.ipynb
