name: readthedocs
channels:
  - conda-forge
dependencies:
  - linkchecker 10.6.*
  - nbconvert 7.17.*
  - python 3.10 # keep in sync with pymin in meta.yaml
  - sphinx 8.1.*
  - sphinx_rtd_theme 3.1.*
  - sphinxcontrib-bibtex 2.7.*
  - tree 2.3.*
